inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "tmp/**/*"
    - "config/initializers/*"
    - "db/migrate/*.rb"
    - !ruby/regexp /old_and_unused\.rb$/
  DisplayCopNames: true
  TargetRubyVersion: 2.6.3

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - 'spec/**/*'

# Rails特有の構文チェック
Rails:
  Enabled: true

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# For rubocop < 1.0.0
Style/HashEachMethods:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformKeys:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformValues:
  Enabled: true

Capybara/FeatureMethods:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

# RSpecのModelテストに自クラスを宣言できる
RSpec/DescribedClass:
  Enabled: false
