inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "tmp/**/*"
    - "config/initializers/*"
    - "db/migrate/*.rb"
    - !ruby/regexp /old_and_unused\.rb$/
  DisplayCopNames: true
  TargetRubyVersion: 2.6.3

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - 'spec/**/*'

# Rails特有の構文チェック
Rails:
  Enabled: true

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# For rubocop < 1.0.0
Style/HashEachMethods:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformKeys:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformValues:
  Enabled: true

# For rubocop < 1.0.0
Lint/RaiseException:
  Enabled: true

# For rubocop < 1.0.0
Lint/StructNewOverride:
  Enabled: true

# For rubocop < new version
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# For rubocop < new version
Style/ExponentialNotation:
  Enabled: true

Capybara/FeatureMethods:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

# RSpecのModelテストに自クラスを宣言できる
RSpec/DescribedClass:
  Enabled: false

RSpec/HookArgument:
  Exclude:
    - 'spec/rails_helper.rb'

# #uppdate_attributeを使用することを避ける（Vridationsをスキップするため）
Rails/SkipsModelValidations:
  Blacklist:
    - 'spec/**/*'

# RSpec exampleの行数を5行以上記述できる
RSpec/ExampleLength:
  Exclude:
    - 'spec/system/*'

# System SpecではExpectを複数記載できる
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/*'