# CircleCI 2.1 を使用
version: 2.1
# 公開されているCircleCI設定を読み込む。version: 2.1以上
orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  build_test_and_deploy:
    jobs:
      - build
      - rubocop_job:
          requires: 
            - build
      - rspec_job:
          requires: 
            - rubocop_job
      - deploy:
          requires:
            - rspec_job
          filters:
            branches:
              only:
                - master

# 実行環境
executors:
  default:
    # コマンドを実行するディレクトリ（リポジトリ）を指定
    working_directory: ~/haito_notice
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          # 元が BUNDLE_PATH=/usr/local/bundle で設定されているので、上書きする
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          # config/database.ymlの内容と一致させる
          PGUSER: postgres
          RAILS_ENV: test
      # $ psql -vで確認したバージョンと合わせる。-alpineが軽量版のため望ましい
      - image: circleci/postgres:12-alpine
        environment:
          # config/database.ymlの内容と一致させる
          POSTGRES_USER: postgres
          POSTGRES_DB: haito_notice_test

jobs:
  build:
    executor: default
    steps:
      # ソースコードを作業ディレクトリにチェックアウトする特別なステップ
      - checkout
      # 依存関係キャッシュを復元
      - restore_dependencies
      # Bundler のバージョンを指定
      - install_bundle
      # Rubyバンドルキャッシュ依存関係を保存
      - save_dependencies
  rubocop_job:
    executor: default
    steps:
      # 初期テンプレ
      - checkout
      - restore_dependencies
      - install_bundle
      - save_dependencies
      # コード解析を実行
      - run:
          name: 静的コード解析を実行（RuboCop）
          command: bundle exec rubocop
  rspec_job:
    executor: default
    steps:
      # 初期テンプレ
      - checkout
      - restore_dependencies
      - install_bundle
      - save_dependencies
      # DBの起動まで待機
      - run:
          name: DBの起動まで待機
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      # DBをセットアップ
      - run:
          name: DBをセットアップ
          command: bin/rails db:schema:load --trace
      # テストを実行
      - run:
          name: テストを実行（RSpec）
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $TEST_FILES
      # テスト結果を保存(タイミング解析)
      # テストサマリー(https://circleci.com/docs/ja/2.0/collect-test-data/)
      # デプロイコンフィグの例(https://circleci.com/docs/ja/2.0/deployment-integrations/)
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

commands:
  restore_dependencies:
    steps:
      - restore_cache:
          name: 依存関係キャッシュを復元
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
  install_bundle:
    steps:
      # Bundler のバージョンを指定
      - run:
          name: Bundler を指定
          command: bundle -v
      # Ruby の依存関係をインストール
      - run:
          name: バンドルをインストール
          command: bundle check || bundle install
  save_dependencies:
    steps:
      # Rubyバンドルキャッシュ依存関係を保存
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle