# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a5289cebaaa046bf084f68e94edf68ad92579ef6b20d5a5d2e2137e248e7baa9d9a856a6f5d5786f066e23483bfa0df03de176e21cc14cb26b713c2d8664072

test:
  secret_key_base: b7cc45252325582811ac8719314d2968ab886d980e7873f95c3316b13b2a909d1db28cfee8d7986c3aa7bb851471f2764d1e2380359d38b0033a9717899bd240

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
